use actix_web::middleware::from_fn;
use utoipa_actix_web::{scope, service_config::ServiceConfig};

use crate::{
    middlewares::auth::{auth_middleware as auth, strict_to},
    modules::{auth::ROLE_ADMIN, experiences::*, projects::modules::*, *},
};

const ADMIN: [&str; 1] = [ROLE_ADMIN];

pub fn routes(cfg: &mut ServiceConfig) {
    cfg.service(scope("/auth").service(auth::login).service(auth::register))
        .service(
            scope("/experiences")
                .service(experiences::many)
                .service(experiences::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(experiences::insert)
                        .service(experiences::update)
                        .service(experiences::delete),
                ),
        )
        .service(
            scope("/tags")
                .service(tags::many)
                .service(tags::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(tags::insert)
                        .service(tags::update)
                        .service(tags::delete),
                ),
        )
        .service(
            scope("/categories")
                .service(categories::many)
                .service(categories::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(categories::insert)
                        .service(categories::update)
                        .service(categories::delete),
                ),
        )
        .service(
            scope("/projects")
                .service(projects::many)
                .service(projects::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(projects::insert)
                        .service(projects::update)
                        .service(projects::delete),
                )
                .service(
                    scope("/{project_id}/blocks")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(projects::submodules::blocks::many_by_project_id)
                        .service(projects::submodules::blocks::insert_by_project_id)
                        .service(projects::submodules::blocks::delete_many_by_project_id),
                )
                .service(
                    scope("/{project_id}/links")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(projects::submodules::links::many_by_project_id)
                        .service(projects::submodules::links::insert_by_project_id)
                        .service(projects::submodules::links::delete_many_by_project_id),
                )
                .service(
                    scope("/{project_id}/tags")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(projects::submodules::tags::many_by_project_id)
                        .service(projects::submodules::tags::insert_by_project_id)
                        .service(projects::submodules::tags::replace_many_by_project_id)
                        .service(projects::submodules::tags::delete_by_project_and_tag_id),
                ),
        )
        .service(
            scope("/blogposts")
                .service(blogposts::many)
                .service(blogposts::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(blogposts::insert)
                        .service(blogposts::update)
                        .service(blogposts::delete),
                ),
        )
        .service(
            scope("/comments")
                .service(comments::many)
                .service(comments::one)
                .service(
                    scope("")
                        .wrap(from_fn(strict_to(&ADMIN)))
                        .wrap(from_fn(auth))
                        .service(comments::insert)
                        .service(comments::update)
                        .service(comments::delete),
                ),
        )
        .service(
            scope("/users").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(users::many)
                    .service(users::one)
                    .service(users::insert)
                    .service(users::update)
                    .service(users::delete),
            ),
        )
        .service(
            scope("/project-blocks").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(project_blocks::many)
                    .service(project_blocks::one)
                    .service(project_blocks::insert)
                    .service(project_blocks::update)
                    .service(project_blocks::delete),
            ),
        )
        .service(
            scope("/project-links").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(project_links::many)
                    .service(project_links::one)
                    .service(project_links::insert)
                    .service(project_links::update)
                    .service(project_links::delete),
            ),
        )
        .service(
            scope("/project-statuses").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(project_statuses::many)
                    .service(project_statuses::one)
                    .service(project_statuses::insert)
                    .service(project_statuses::update)
                    .service(project_statuses::delete),
            ),
        )
        .service(
            scope("/project-types").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(project_types::many)
                    .service(project_types::one)
                    .service(project_types::insert)
                    .service(project_types::update)
                    .service(project_types::delete),
            ),
        )
        .service(
            scope("/project-ai_usages").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(project_ai_usages::many)
                    .service(project_ai_usages::one)
                    .service(project_ai_usages::insert)
                    .service(project_ai_usages::update)
                    .service(project_ai_usages::delete),
            ),
        )
        .service(
            scope("/experiences-tags").service(
                scope("")
                    .wrap(from_fn(strict_to(&ADMIN)))
                    .wrap(from_fn(auth))
                    .service(experiences_tags::insert_one)
                    .service(experiences_tags::insert_many)
                    .service(experiences_tags::replace_many_by_experience_id)
                    .service(experiences_tags::delete),
            ),
        );
}
