use crate::{
    middlewares::auth::{auth_middleware, strict_to},
    modules::{auth::ROLE_ADMIN, experiences::*, projects::modules::*, *},
};

pub fn routes(cfg: &mut actix_web::web::ServiceConfig) {
    cfg.service(
        actix_web::web::scope("/auth")
            .service(auth::login)
            .service(auth::register),
    )
    .service(
        actix_web::web::scope("/experiences")
            .service(experiences::many)
            .service(experiences::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(experiences::insert)
                    .service(experiences::update)
                    .service(experiences::delete),
            ),
    )
    .service(
        actix_web::web::scope("/tags")
            .service(tags::many)
            .service(tags::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(tags::insert)
                    .service(tags::update)
                    .service(tags::delete),
            ),
    )
    .service(
        actix_web::web::scope("/categories")
            .service(categories::many)
            .service(categories::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(categories::insert)
                    .service(categories::update)
                    .service(categories::delete),
            ),
    )
    .service(
        actix_web::web::scope("/projects")
            .service(projects::many)
            .service(projects::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(projects::insert)
                    .service(projects::update)
                    .service(projects::delete),
            )
            .service(
                actix_web::web::scope("/{project_id}/blocks")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(projects::submodules::blocks::many_by_project_id)
                    .service(projects::submodules::blocks::insert_by_project_id)
                    .service(projects::submodules::blocks::delete_many_by_project_id),
            )
            .service(
                actix_web::web::scope("/{project_id}/links")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(projects::submodules::links::many_by_project_id)
                    .service(projects::submodules::links::insert_by_project_id)
                    .service(projects::submodules::links::delete_many_by_project_id),
            )
            .service(
                actix_web::web::scope("/{project_id}/tags")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(projects::submodules::tags::many_by_project_id)
                    .service(projects::submodules::tags::insert_by_project_id)
                    .service(projects::submodules::tags::replace_many_by_project_id)
                    .service(projects::submodules::tags::delete_by_project_and_tag_id),
            ),
    )
    .service(
        actix_web::web::scope("/blogposts")
            .service(blogposts::many)
            .service(blogposts::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(blogposts::insert)
                    .service(blogposts::update)
                    .service(blogposts::delete),
            ),
    )
    .service(
        actix_web::web::scope("/comments")
            .service(comments::many)
            .service(comments::one)
            .service(
                actix_web::web::scope("")
                    .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                    .wrap(actix_web::middleware::from_fn(auth_middleware))
                    .service(comments::insert)
                    .service(comments::update)
                    .service(comments::delete),
            ),
    )
    .service(
        actix_web::web::scope("/users").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(users::many)
                .service(users::one)
                .service(users::insert)
                .service(users::update)
                .service(users::delete),
        ),
    )
    .service(
        actix_web::web::scope("/project-blocks").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(project_blocks::many)
                .service(project_blocks::one)
                .service(project_blocks::insert)
                .service(project_blocks::update)
                .service(project_blocks::delete),
        ),
    )
    .service(
        actix_web::web::scope("/project-links").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(project_links::many)
                .service(project_links::one)
                .service(project_links::insert)
                .service(project_links::update)
                .service(project_links::delete),
        ),
    )
    .service(
        actix_web::web::scope("/project-statuses").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(project_statuses::many)
                .service(project_statuses::one)
                .service(project_statuses::insert)
                .service(project_statuses::update)
                .service(project_statuses::delete),
        ),
    )
    .service(
        actix_web::web::scope("/project-types").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(project_types::many)
                .service(project_types::one)
                .service(project_types::insert)
                .service(project_types::update)
                .service(project_types::delete),
        ),
    )
    .service(
        actix_web::web::scope("/project-ai_usages").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(project_ai_usages::many)
                .service(project_ai_usages::one)
                .service(project_ai_usages::insert)
                .service(project_ai_usages::update)
                .service(project_ai_usages::delete),
        ),
    )
    .service(
        actix_web::web::scope("/experiences-tags").service(
            actix_web::web::scope("")
                .wrap(actix_web::middleware::from_fn(strict_to(vec![ROLE_ADMIN])))
                .wrap(actix_web::middleware::from_fn(auth_middleware))
                .service(experiences_tags::insert_one)
                .service(experiences_tags::insert_many)
                .service(experiences_tags::replace_many_by_experience_id)
                .service(experiences_tags::delete),
        ),
    );
}
